import setuptools

setuptools.setup(
    name="parallel-execute",
    install_requires=["concurra>=1.0.8"],
    version="2.0.3",
    author="Sahil Pardeshi",
    author_email="sahilrp7@gmail.com",
    description="Python wrappers for easy multiprocessing and threading",
    long_description=open('README.rst').read(),
    url="https://github.com/parallel-execute/parallel-execute",
    packages=setuptools.find_packages(),
    license='MIT License',
    python_requires=">=3.6",
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3",
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
        'Programming Language :: Python :: Implementation :: CPython',
        'Topic :: Software Development :: Libraries',
        'Topic :: System :: Distributed Computing',
        "Intended Audience :: Developers",
        "Intended Audience :: Information Technology",
        "Intended Audience :: System Administrators",
        "Intended Audience :: Science/Research",
        "Operating System :: OS Independent",
    ]
)
